version: "3.5"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"
    volumes:
      - postgres-data:/var/lib/postgresql
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
  rabbitmq-admin:
    image: nasqueron/rabbitmqadmin
    #volumes:
    #  - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rabbitmq
    ports:
      - "15672:15672"
volumes:
  postgres-data:
